title: Priyansh Gupta
description: Software Engineer
baseurl: ''
username: Priyansh Gupta
typing_text: Software Engineer
email: guptapriyansh1907@gmail.com
github_username: priyansh19
codepen_username: null
dev_username: null
linkedin_username: priyansh-gupta-649048159
twitter_username: priyansh1907
show_aboutme_card: true
about_me_title: Who Am I ?

show_skills_card: true
skills_title: Skills
show_timeline_card: true
timeline_title: Education & Experience 
cv_download_link: 'https://bit.ly/3b4sbdq'
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: true
os_projects_title: Open Source Projects
show_contact_card: true
contact_title: Get in touch ..
repository: priyansh19/great-spider
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects: null
google-analytics:
  id: UA-158757509-2
plugins:
  - jekyll-github-metadata
exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
url: ''
