title: Priyansh Gupta
description: Software Engineer
baseurl: ''
username: Priyansh Gupta
typing_text: Software Engineer
email: guptapriyansh1907@gmail.com
github_username: priyansh19
codepen_username: priyansh19
dev_username: priyansh19
linkedin_username: priyansh-gupta-649048159
twitter_username: priyansh1907
show_aboutme_card: true
about_me_title: Who Am I ?

show_skills_card: false
skills_title: Skills
show_timeline_card: true
<<<<<<< HEAD
timeline_title: Education & Experience ..
=======
timeline_title: Education & Experience
>>>>>>> local-server
cv_download_link: 'https://example.com/'
show_projects_card: false
show_projects: false
projects_title: Projects
show_os_projects: false
os_projects_title: Open Source Projects
show_contact_card: false
contact_title: Contact
contact_description: >-
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
  eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
  voluptua. At vero eos et accusam et justo duo dolores et ea rebum. If you like
  this theme and want to use it for yourself, checkout the source code and the
  documentation at <a class="highlight-link"
  href="https://github.com/longpdo/neumorphism" target="_blank"
  rel="noreferrer"> Github </a>.
repository: longpdo/neumorphism
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects: null
google-analytics:
  id: UA-158757509-2
plugins:
  - jekyll-github-metadata
exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
url: ''
