title: Neumorphism
description: Personal website powered by Jekyll
baseurl: ''
username: Neumorphism
typing_text: Jekyll Theme
email: email@example.com
github_username: longpdo
codepen_username: exampleUser
dev_username: exampleUser
linkedin_username: exampleUser
twitter_username: exampleUser
show_aboutme_card: true
about_me_title: About Me
about_me_description: >-
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
  eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
  voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita
  kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  Lorem
  ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
  tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
  vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
  gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. If you like
  this theme and want to use it for yourself, checkout the source code and the
  documentation at <a class="highlight-link"
  href="https://github.com/longpdo/neumorphism" target="_blank"
  rel="noreferrer"> Github </a>. You can also find me on <a
  class="highlight-link"
  href="https://jamstackthemes.dev/theme/jekyll-neumorphism/" target="_blank"
  rel="noreferrer">JAMstack Themes</a> and on <a class="highlight-link"
  href="https://jekyll-themes.com/neumorphism/" target="_blank"
  rel="noreferrer">Jekyll Themes</a>.
show_skills_card: true
skills_title: Skills
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: 'https://example.com/'
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: true
os_projects_title: Open Source Projects
show_contact_card: true
contact_title: Contact
contact_description: >-
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
  eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
  voluptua. At vero eos et accusam et justo duo dolores et ea rebum. If you like
  this theme and want to use it for yourself, checkout the source code and the
  documentation at <a class="highlight-link"
  href="https://github.com/longpdo/neumorphism" target="_blank"
  rel="noreferrer"> Github </a>.
repository: longpdo/neumorphism
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects: null
google-analytics:
  id: UA-158757509-2
plugins:
  - jekyll-github-metadata
exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
url: ''
